from common import an, GITLAB_ENV, PARTIAL

E = GITLAB_ENV

GITLAB = [
{
 "slug": "stack_template_project_launch",
 "skills": ["R8", "A2"],
 "chain": "derive which built-in project template matches a described technology stack, then create the project from that template with the stated name and visibility",
 "entities": "templates at /projects/new#create_from_template (components/create/templates.js): Android, NodeJS, Jekyll, HTML/GitLab Pages, blank - 5 choices, no near-duplicates. Namespace byteblaze (12 own projects). No superlative is involved, so there is no tie exposure at all; the only ambiguity risk is a stack description that fits two templates, so the description must name one framework the template list carries verbatim.",
 "writeback": "newProjects[] + nextIds.project, plus the template's seeded repo.fileOverlay / treeOverlay entries (mutations.js:272 createProject)",
 "analogues": an("gitlab", 178, 179, 180, 181),
 "notes": E + " Route: navbar + menu -> New project -> 'Create from template'. Keep every A2 field dictated (name, visibility, description) so the lane stays a pure creation form and the only derived thing is the template choice - otherwise the lane drifts into A7. Do NOT bolt a members step on: batch 5's template_project_staffed was R8->A2->A3->A12 and batch 6 truncates it to the 2-skill core, so the A3 half belongs to phrase_search_grant_access, not here. /explore and /dashboard/projects default to name_asc alphabetical at 20/page (components/ui/ProjectsNav.jsx:48), so a created project named late in the alphabet lands on page 2 - never grade 'it appears on page 1'. getMrDiff() returns null for any MR not in the seed, so a created project's Commits/Changes/Pipelines tabs render empty and must never be graded. " + PARTIAL + " Batch-5 adjacent: template_project_staffed.",
},
{
 "slug": "licence_obligation_commit",
 "skills": ["R8", "A7"],
 "chain": "match a described licensing obligation (copyleft / patent grant / attribution-only) to one of the 13 licences in the picker, then commit that licence text as a file in the named repo",
 "entities": "byteblaze/cloud-to-butt, byteblaze/timeit, byteblaze/solarized-prism-theme, byteblaze/gimmiethat.space, byteblaze/dotfiles. Licence dropdown is 13 entries grouped Popular/Other (components/create/licenses.js:83) with no near-duplicates, so the described obligation resolves uniquely (copyleft -> gpl-3.0).",
 "writeback": "repo.fileOverlay[\"<full_path>:<default_branch>:LICENSE\"] plus treeOverlay and commitOverlay (mutations.js:229 commitToRepo -> :155 writeFiles); readback via /-/blob",
 "notes": E + " CRITICAL (CORRECTIONS #15): 134 of 175 projects do NOT default to main, and four of byteblaze's twelve - cloud-to-butt, timeit, solarized-prism-theme, millennials-to-snake-people - are on master. NewFile takes params.ref verbatim without validating it, so /-/new/main renders and the commit lands on a branch the repo does not have, invisible on the default branch: a reward keyed on ':main:LICENSE' scores a CORRECT run 0.0. Resolve default_branch from src/data/projects.json for every entity before writing the overlay key. CORRECTIONS #17: a11yproject/a11yproject.com renders an 'Add LICENSE' chip although it HAS one, because the file is LICENSE-APLv2 and ProjectOverview's /^licen[cs]e(\\.\\w+)?$/i test rejects it - so 'the repo of mine with no licence' is not a usable retrieval. " + PARTIAL + " Batch-5 adjacent: copyleft_license_commit - change the obligation described and the target file/branch, not merely which repo.",
 "analogues": an("gitlab", 73, 71, 72, 166),
},
{
 "slug": "fork_named_upstream_solo",
 "skills": ["R9", "A2"],
 "chain": "resolve the named upstream project to its actual namespace on this instance, then fork it into byteblaze through the fork form",
 "entities": "root/metaseq (project id 33) - NOT facebook/metaseq; yjlou/2019-nCov; kkroening/ffmpeg-python; eriklindernoren/PyTorch-GAN; auth0/angular-storage; koush/AndroidAsync. The facebook namespace holds only buck (60) and create-react-app (122).",
 "writeback": "newProjects[] + repo.forkOrigin.<full_path> + nextIds.project; the source project gains projectEdits.<id>.forks_count",
 "notes": E + " CORRECTIONS #22: facebook/metaseq does not exist here - MetaSeq is root/metaseq, and pages/ForkProject.jsx:13 already renders the header as root/metaseq. An official intent names entities as they exist on the real site; resolve every entity against src/data/, never against the benchmark string. The R9 half is exactly that resolution, which is what keeps the retrieval load-bearing. Never phrase the retrieval as 'the most-forked' - every forks_count is <= 1, a mass tie, and sortProjects has no forks ordering so there is no list view for it either. getMrDiff() returns null for a created project's MRs. " + PARTIAL + " Batch-5 adjacent: fork_and_staff_* (R9->A2->A3); batch 6 keeps only the fork.",
 "analogues": an("gitlab", 66, 68, 69),
},
{
 "slug": "named_issue_assign_due",
 "skills": ["R9", "A12"],
 "chain": "look up the named repository, then create an issue in it and link it in the same pass to an assignee and a due date",
 "entities": "byteblaze/dotfiles, byteblaze/empathy-prompts, byteblaze/cloud-to-butt, a11yproject/a11yproject.com, byteblaze/a11y-syntax-highlighting. Assignee candidates are ALL 2,199 users, not just members (components/issuable/Controls.jsx:47-62 carries an explicit comment that restricting to members would break the anchored official tasks). 19,705 issues exist, so iid allocation must clear nextIds.",
 "writeback": "newIssues[] with assignee_ids and due_date, plus nextIds.issue",
 "notes": E + " Use the per-issue creation form, never the bulk sidebar: IssuablesList.jsx:636-638 restricts the BULK assignee select to project members, while the per-issue picker offers all 2,199 users - keeping both is deliberate parity and must not be 'fixed'. byteblaze owns ZERO milestones (only 32 of 175 projects have any), so do not add a milestone component; nextIds.milestone seeds at 590 and must be cleared if one is ever created. Issue lists page at 20 (IssuablesList.jsx:29) newest-first by created_date, so a created issue lands on page 1. closed_at is null on every seeded issue by design, making ?sort=closed_at inert. " + PARTIAL + " Batch-5 adjacent: top_contributor_join_issue (R4->R7->A12) - batch 6 drops the join and names the repo outright.",
 "analogues": an("gitlab", 145, 146, 147, 199),
},
{
 "slug": "star_named_repo_follow",
 "skills": ["R9", "A9"],
 "chain": "resolve the named user or project from the search box or a byline, then follow that user / star that project",
 "entities": "users kentonv (Kenton Varda, Austin TX, org @cloudflare, User ID 620 - verified live), wing328, dpvc, manast, KATT, Reputeless, kahun, dehenne; projects umano/AndroidSlidingUpPanel (55 stars), facebook/create-react-app (52). User search 'Kenton Varda' -> @kentonv verified live. follows.json holds only 5 rows, all touching byteblaze.",
 "writeback": "a follow writes newFollows + userEdits.<follower> AND userEdits.<followee> (both records, UserProfile.jsx:266); a star writes newStars + projectEdits.<id> (ProjectOverview.jsx:262)",
 "notes": E + " Never grade a follower COUNT: UserProfile.jsx:254-257 derives followers/following from state.follows, which has 5 rows, so every one of the 2,198 non-byteblaze profiles shows 0 - official 186 has no usable analogue. users[].followers exists as an integer and the profile does not render it (third instance of 'a writable key is not the key the page reads'). sortProjects ranks on p.star_count (pages/hooks.js:357), NOT on the stars array, so injecting newStars alone moves no ranking - use projectEdits.<id>.star_count if a rank must be changed, and keep the nudge plausible (byteblaze's twelve projects span 0-6 stars). Search covers 5 scopes and matches title+description only; there is no notes scope. " + PARTIAL,
 "analogues": an("gitlab", 112, 113, 114, 115),
},
{
 "slug": "filtered_issue_single_field",
 "skills": ["R5", "A1"],
 "chain": "narrow the issue list with a compound token filter plus a sort, then edit exactly one field on the single row that selects",
 "entities": "primer/design (2,095 user notes, 40 labels, >1 member), a11yproject/a11yproject.com (30 issues in issues_index vs a stored open_issues_count of 40), opensourcediversity/opensourcediversity.org. These three are the only label-carrying projects with more than one member. Filter vocabulary (pages/hooks.js:61): state, search + in=TITLE|DESCRIPTION, label_name[] incl. None/Any and multi-label AND, not[label_name][], milestone_title incl. Upcoming/Started, assignee_username[]/assignee_id=None|Any, author_username, reviewer_username, first_page_size, page. Nine sorts.",
 "writeback": "issueEdits.<id>.assignee_ids / .due_date / .milestone_id / .title (IssueDetail.jsx:438,514; EditIssue.jsx:53)",
 "notes": E + " DO NOT use byteblaze/a11y-webring.club (CORRECTIONS #19): all four of its open issues are ALREADY assigned to byteblaze, so an assignee component is pre-satisfied at t=0 and the untouched state would score, and it has exactly one member. CORRECTIONS #10 (a correction to a correction): the state-tab badges ARE filter-aware - IssuesList.jsx:35 calls issuableStateCounts(rows, q, indexes) and hooks.js:39-50 re-runs filterIssuables with state forced to all; the unfiltered counts at IssuablesList.jsx:888 are DEAD CODE that the census mistook for the render path. So 'how many open issues carry label X' CAN be read off the badge. CORRECTIONS #20: projects.json.open_issues_count is a stored counter diverging from the list by up to 14x (openapi-generator 3,476 vs 243, keycloak 1,604 vs 128, a11yproject.com 40 vs 30) - rank on it if you must, never ask the agent to reproduce it. CORRECTIONS #18: the bulk Subscriptions field is write-only (IssuablesList.jsx:657 writes patch.subscribed while IssueDetail.jsx:136 renders from state.ui.unsubscribed) - never grade it. Lists page at 20. " + PARTIAL + " Batch-5 adjacent: label_triage_bulk (R5->A4) - batch 6 swaps the bulk action for a single-field edit so the pair is new.",
 "analogues": an("gitlab", 19, 20, 24, 89),
},
{
 "slug": "review_queue_comment",
 "skills": ["R5", "A8"],
 "chain": "filter the merge-request queue by reviewer/assignee, state and sort, then post a comment on the row that selects",
 "entities": "byteblaze has 6 assigned MRs of which 2 are open (a11yproject/a11yproject.com!1270, !1485) plus byteblaze/a11y-webring.club!40; 159 review-requested MRs; 19,280 threads carry >=2 user notes; trpc/trpc holds 3,197 user notes and a11yproject/a11yproject.com 2,368. Route: navbar /dashboard/merge_requests, or project -> Merge requests.",
 "writeback": "newNotes[] + mergeRequestEdits.<id>.user_notes_count (NotesTimeline.jsx:321 postComment -> :326 appendTo('notes'), :335 bumps the count)",
 "notes": E + " There is NO threaded Reply control on gitlab: grep -i reply pages/NotesTimeline.jsx returns nothing and the page renders exactly one top-level comment box, so 'reply to the first reply' is inexpressible here (it IS expressible on reddit - do not carry the shape across sites). The specific MRs in official 75-77 carry only SYSTEM notes (byteblaze/a11y-webring.club!40 has three) - draw from the 19,280 multi-note threads instead. Search matches title and description only, so the retrieval must be a filter, not a note-body search. " + PARTIAL + " Batch-5 adjacent: stale_review_nudge (R5->R4->A8) - batch 6 drops the ordinal step and keeps the filter as the whole retrieval.",
 "analogues": an("gitlab", 60, 61, 62, 65),
},
{
 "slug": "contributor_counts_file",
 "skills": ["R4", "A7"],
 "chain": "read the top-N contributors and their commit counts off the Contributors graph, then commit that ordered list as a file in a repo",
 "entities": "OpenAPITools/openapi-generator (William Cheng 2059 vs 182, margin 1877), mathjax/MathJax (Davide P. Cervone 2101 vs 121, 1980), OptimalBits/bull (Manuel Astudillo 965 vs 60, 905), cppmap/cppmap.docs (Ryo Suzuki 484 vs 19, 465), trpc/trpc (Alex/KATT 1080 vs 755, 325). Sink repo byteblaze/gimmiethat.space.",
 "writeback": "repo.fileOverlay[\"<sink full_path>:<sink default_branch>:<path>\"] + treeOverlay + commitOverlay",
 "notes": E + " Pin every commit count to /-/graphs/:ref (Contributors.jsx:158,161). commits.json is capped at 40 rows per ref (min 1, max 40, median 6 across all 173 project entries), so three surfaces give three answers for byteblaze/dotfiles: overview 553, Contributors 552, Repository Analytics 40 - and RepoAnalytics.jsx:53 aggregates the capped source knowingly. CORRECTIONS #26: every census tie audit is rank-1 only. kkroening/ffmpeg-python has a wide top-1 margin and its rank-3/rank-4 boundary is TIED at 5 commits, so it is unusable for a top-3 task - check rank N against rank N+1 for the exact slice each task uses. Do not use a11yproject/a11yproject.com: Eric Bailey appears TWICE (422 and 410, two emails) because Contributors.jsx:20-22 groups by e-mail and deliberately does not de-duplicate - fine for 'who', fatal for 'how many'. contributors.json is a frozen bundled import with NO state overlay (dataManager.js:656), so no injection can re-rank or extend this pool; getCommits() does merge repo.commitOverlay but that only widens the disagreement. Resolve the sink's default_branch before writing the overlay key (CORRECTIONS #15). " + PARTIAL + " Batch-5 adjacent: contributor_honour_roll (R4->R3->A7) - batch 6 folds the count into the ordinal step.",
 "analogues": an("gitlab", 49, 50, 52, 53),
},
{
 "slug": "top_starred_bulk_star",
 "skills": ["R4", "A4"],
 "chain": "order the public project list by stars, then star every project down to the stated rank",
 "entities": "/explore/projects/starred sorted stars_desc: umano/AndroidSlidingUpPanel 55, facebook/create-react-app 52, then 51. Top-1 margin 3; top-3 boundary margin 4 (51 vs 47) - SAFE. Top-4/top-5 boundary margin is only 1 (46 vs 45, 43 vs 42). Top-10 has exact TIES at 42 (openapi-generator, autojump) and at 39 (capnproto, PyAV) - do not use.",
 "writeback": "newStars[] x N + projectEdits.<id> per starred project (ProjectOverview.jsx:262 toggleStar, button at :322)",
 "notes": E + " Cap N at 3. There is no bulk-star control anywhere - starring N projects is N separate project visits, which is exactly what official 107-111 require, so the 'bulk' here is repetition over a matched set, not a mass action. /explore excludes private projects (ExploreProjects.jsx:44) and the Most-stars tab additionally drops star_count == 0, so the superlative must be scoped to public projects. sortProjects ranks on star_count, so a tie can only be broken through projectEdits.<id>.star_count - newStars alone changes nothing, and the reward must recompute the superlative from the injected state rather than hard-coding the seed answer. Explore pages at 20. Never use 'my most-starred repo': byteblaze's top two are TIED at 6 (empathy-prompts, millennials-to-snake-people). " + PARTIAL + " Batch-5 adjacent: star_top3_record_bio (R1->R4->A9->A4->A1) - batch 6 keeps only the ordinal and the bulk apply.",
 "analogues": an("gitlab", 107, 109, 110, 111),
},
{
 "slug": "phrase_search_grant_access",
 "skills": ["R6", "A3"],
 "chain": "find the project by a phrase in its title or description through the navbar search, then invite the named users to it at a stated role",
 "entities": "Search.jsx:68-86 offers 5 scopes (projects, issues, merge_requests, milestones, users); 175 projects, 183 seeded members, and ANY of the 2,199 users is invitable. Roles Guest/Reporter/Developer/Maintainer/Owner via the native select in the Invite members modal (verified live on byteblaze/gimmiethat.space).",
 "writeback": "newMembers[] (MembersTable.jsx:198 -> mutations.js:363 addMembers)",
 "notes": E + " Search matches TITLE and DESCRIPTION only - there is no notes scope, so never phrase the retrieval as 'the project whose issue mentions X'. Route: project -> Project information (lands on /activity) -> Members; the two-click gesture is required because sub-items never appear on hover. Do not reproduce official 182's string or its kkroening/ffmpeg-python entity verbatim. The per-row Max-role dropdown (MembersTable.jsx:219) and removal (:227) are separate shapes if a variant needs them. " + PARTIAL,
 "analogues": an("gitlab", 134, 135, 136, 138),
},
{
 "slug": "symptom_issue_self_assign",
 "skills": ["R6", "A1"],
 "chain": "search the issue corpus for a described symptom, then assign the single matching issue to myself",
 "entities": "primer/design (2,095 user notes, 40 labels), a11yproject/a11yproject.com, byteblaze/empathy-prompts, keycloak/keycloak, OpenAPITools/openapi-generator. 19,705 issues across 175 projects, so a phrase that matches exactly one title is easy to find and must be verified to match exactly one.",
 "writeback": "issueEdits.<id>.assignee_ids",
 "notes": E + " Official 195, 201 and 202 are this exact shape - do NOT reproduce their strings; change both the symptom and the repo. 'Assign issue X to Y' on an existing issue is classified A1 (single-field edit) by the census; A3 is reserved for project/group membership. Search covers title+description only across 5 scopes. Controls.jsx:47-62 offers all 2,199 users on the per-issue sidebar, so a self-assign and an assign-to-a-non-member are both reachable. Verify the phrase resolves to ONE issue against src/data/issues_index.json, not against the rendered search page. " + PARTIAL + " Batch-5 adjacent: mention_participant_assign (R6->A1->A8) - batch 6 drops the @mention comment, which is the A8 half and belongs to review_queue_comment.",
 "analogues": an("gitlab", 88, 195, 201, 202),
},
{
 "slug": "label_count_milestone",
 "skills": ["R3", "A2"],
 "chain": "count the issues matching a compound label/state filter, and if the count clears the stated threshold create the cleanup milestone in that project with dictated title, dates and description",
 "entities": "94 of 175 projects carry labels (1,254 labels total). The three label-carrying projects with more than one member are primer/design, a11yproject/a11yproject.com and opensourcediversity/opensourcediversity.org. byteblaze owns ZERO milestones and only 32 of 175 projects have any, so the milestone always has to be created rather than found. Milestone form fields verified: milestone[title|start_date|due_date|description].",
 "writeback": "newMilestones[] + nextIds.milestone (NewMilestone.jsx:64)",
 "notes": E + " The count is READABLE: CORRECTIONS #10 established the state-tab badges are filter-aware (IssuesList.jsx:35 -> hooks.js:39-50), reversing the census. But CORRECTIONS #20/#102: projects.json.open_issues_count is a stored counter that disagrees with the list by up to 14x, so the instruction MUST name which surface is authoritative ('on the issues list', not 'on the project card') - a terse instruction may omit the click path but may not omit which of two disagreeing surfaces it means. nextIds.milestone seeds at 590; verify the counter before asserting on any generated id, or a milestone the agent then creates collides. Keep the milestone's own fields dictated so the action stays A2 and does not drift into A7. Route: project -> Issues -> Milestones -> New milestone. " + PARTIAL,
 "analogues": an("gitlab", 140, 143, 54, 3),
},
{
 "slug": "computed_window_milestone",
 "skills": ["R2", "A2"],
 "chain": "perform the relative-date arithmetic the instruction states (start on date D, end N days later inclusive / end of Qx of year Y), then create the milestone with the computed start and due dates",
 "entities": "any byteblaze/* project - none has a milestone, so there is nothing to collide with. Official phrasings that work verbatim as shapes: 'starting on January 16, 2030 and ending in 20 days (inclusive)', 'ending at the end of Q1 2033', 'due 2030-1-3'.",
 "writeback": "newMilestones[].start_date and .due_date (both ISO dates), + title, + nextIds.milestone",
 "notes": E + " The window must be stated in the instruction and computed by the agent. NEVER use a wall-clock-relative window ('last quarter', 'the next 30 days'): the only period control in the whole mock is the CI/CD analytics switcher (PipelinesCi.jsx:1156) and it computes its range from new Date() at :1265-1274, so its output changes every day and it is not gradeable. /-/graphs/:ref/charts has no configuration control at all. R10 is 0% of official gitlab - do not build gitlab tasks on report configuration. Off-by-one is the whole difficulty here, so pick windows where inclusive and exclusive readings differ visibly and state 'inclusive' explicitly, as official 141/142/144 do. " + PARTIAL + " Batch-5 adjacent: milestone_kickoff (R2->A2->A12) - batch 6 drops the kickoff issue.",
 "analogues": an("gitlab", 141, 142, 144, 143),
},
{
 "slug": "top_contributor_grant_access",
 "skills": ["R7", "A3"],
 "chain": "read a project's top committer off the Contributors graph, join that display name to a user account through the user search, then grant that account a stated role on a second project",
 "entities": "verified name-joins with margins: OpenAPITools/openapi-generator -> William Cheng 2059 vs 182 (1877) -> @wing328; mathjax/MathJax -> Davide P. Cervone 2101 vs 121 (1980) -> @dpvc; OptimalBits/bull -> Manuel Astudillo 965 vs 60 (905) -> @manast; cppmap/cppmap.docs -> Ryo Suzuki 484 vs 19 (465) -> @Reputeless; trpc/trpc -> Alex/KATT 1080 vs 755 (325) -> @KATT; kahun/awesome-sysadmin -> Francisco Augusto 57 vs 13 (44) -> @kahun; dehenne/awesome-visibility -> Henning Leutz 51 vs 3 (48) -> @dehenne; capnproto/capnproto -> Kenton Varda 884 vs 844 - margin only 40, use with care.",
 "writeback": "newMembers[] on the sink project",
 "notes": E + " The ONLY join key is the display name: 0 of 3,460 contributor rows match a users.json email, because dataManager.js:676 records that user emails were deliberately anonymised to @fakegithub.com while contributors.json keeps the real commit addresses, and projectRoleFor matches on name first precisely for that reason. Do not 'fix' it by injecting userEdits.<id>.email - it undoes a deliberate seed decision and buys nothing, since the name-join already works for 83 of 175 projects. Never ask for the joined contributor's FOLLOWER count (official 186): follows.json has 5 rows and every non-byteblaze profile shows 0. Do not use a11yproject/a11yproject.com (Eric Bailey appears twice at 422 and 410). contributors.json has no state overlay, so this entity pool is fixed at 83 and cannot be widened by injection. R7 is 9% of official gitlab - keep this to one lane. " + PARTIAL + " Batch-5 adjacent: top_contributor_join_issue (R4->R7->A12) - batch 6 keeps the join and swaps the action to a membership grant.",
 "analogues": an("gitlab", 187, 183, 136, 132),
},
{
 "slug": "most_starred_match_fork",
 "skills": ["R1", "A2"],
 "chain": "identify the most-starred public project matching a described category, then fork it into byteblaze",
 "entities": "instance-wide most-starred is umano/AndroidSlidingUpPanel at 55 (runner-up 52, margin 3) - safe. Any CATEGORY-scoped superlative (GAN implementation, Covid tracker, ChatGPT tooling) must be enumerated by hand against src/data/projects.json and its margin measured before use; the census's own site-wide list already ties at 42 and at 39.",
 "writeback": "newProjects[] + repo.forkOrigin.<full_path>; the source gains projectEdits.<id>.forks_count (mutations.js:452 forkProject)",
 "notes": E + " Fork is classified A2 by the census because the fork form picks namespace and visibility. 'My most-starred repo' is DEAD: byteblaze's top two are tied at 6 (empathy-prompts = millennials-to-snake-people), which is exactly what official 15/16 hit; scope the superlative instance-wide or to an enumerated category. /explore drops private projects and the Most-stars tab drops star_count == 0. sortProjects reads p.star_count, so a tie is only breakable through projectEdits.<id>.star_count, the reward must recompute from the injected state, and the nudge must stay plausible (byteblaze's twelve span 0-6 stars, so 8 fixes a tie and 500 turns retrieval into anomaly-spotting). Do not reproduce official 67 or 38 verbatim. " + PARTIAL,
 "analogues": an("gitlab", 67, 38, 37, 15),
},
]
